### ISSUE TITLE
后台菜单中权限管理中的config读取配置错误

### ISSUE THREAD

**Issue by Aexus** [lanceWan/IAdmin#1]
后台权限管理中，用户管理，权限管理，文章管理，权限管理。这几个的资源库(app/Repositiories/ArticleRepository.php....)，里面读取config的关键字(global)写错了，你那里写为golbal,你需要修改下，不然放在服务器上，总报错。 其中UserRepository.php中的ajaxIndex方法中$start = request('start', config('admin.global.list.start')); /*获取开始*/
		$length = request('length', config('admin.global.list.length')); ///*获取条数*/的list也写错了。

**Comment by lanceWan** [comment]
@Aexus   非常感谢，有时候打字总是错误 ~~
